# Site settings
title:  
SEOTitle: yu0d | BY Blog
header-img: img/post-bg-desk.jpg
email: yu@gmail.com
description: "Every failure is leading towards success."
keyword: "BY, BY Blog, yu0d, qiubaiying, yu0d, iOS, Apple, iPhone"
url: "http://yu0d.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
#github_repo: "https://github.com/qiubaiying/qiubaiying.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Goals determine what you going to be!"
sidebar-avatar: /img/about-BY-gentle.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`


<!-- Gitalk 评论 start  -->

<!-- Link Gitalk 的支持文件  -->
<link rel="stylesheet" href="https://unpkg.com/gitalk/dist/gitalk.css">
<script src="https://unpkg.com/gitalk@latest/dist/gitalk.min.js"></script> 
<div id="gitalk-container"></div>     <script type="text/javascript">
    var gitalk = new Gitalk({
    distractionFreeMode: true,
    // gitalk的主要参数
	clientID: `8a19ee0394cd022682e9`,
	clientSecret: `54cb49e991003105952a6e5fe0be3bfc49ef6f07`,
	repo: `yu0d.github.io`,
	owner: 'Github yu0d',
	admin: ['Github yu0d'],
	id: 'yu0d.github.io.kai',
    
    });
    gitalk.render('gitalk-container');
</script> 
<!-- Gitalk end -->



# SNS settings
RSS: false
# weibo_username:     qiubaiying
zhihu_username:      
github_username:    
facebook_username:  
jianshu_username:   
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
disqus_username: yu0d

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: f2c84e7629bb1446c1a4                            #生成的clientID
  clientSecret: ca6d6139d1e1b8c43f8b2e19492ddcac8b322d0d    #生成的clientSecret
  repo: yu0d.github.io    #仓库名称
  owner: yu0d    #github用户名
  admin: yu0d
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
#ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
#ga_domain:                # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: false                     # 是否使用首页标签
featured-condition-size: 0              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
#    <!-- {
#       title: "WY",
#        href: "http://zhengwuyang.com"
#    },{
#        title: "Apple",
#        href: "https://apple.com"
#    },{
#        title: "Apple Developer",
#        href: "https://developer.apple.com/"
#    }, -->
    {
        title: "简书·BY",
        href: "http://www.jianshu.com/u/b2a6f1754316"
    },
    {
      title: "神秘大佬",
      href: "http://loseme.top/"
    }
]
